// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_basic_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_x_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_x_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_x_zsubpop_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_x_zsubpop_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_zsubpop_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Correlated_zsubpop_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Overdispersed_Stan_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_basic_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_x_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_x_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_x_zsubpop_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_x_zsubpop_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_zglobal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_zsubpop_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Uncorrelated_zsubpop_zglobal_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4Correlated_basic_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_basic_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_x_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_x_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_x_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_x_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_x_zsubpop_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_x_zsubpop_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_x_zsubpop_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_x_zsubpop_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_zsubpop_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_zsubpop_mod, 0},
    {"_rcpp_module_boot_stan_fit4Correlated_zsubpop_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Correlated_zsubpop_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Overdispersed_Stan_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Overdispersed_Stan_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_basic_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_basic_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_x_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_x_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_x_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_x_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_x_zsubpop_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_x_zsubpop_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_x_zsubpop_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_x_zsubpop_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_zglobal_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_zsubpop_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_zsubpop_mod, 0},
    {"_rcpp_module_boot_stan_fit4Uncorrelated_zsubpop_zglobal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Uncorrelated_zsubpop_zglobal_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_networkscaleup(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
