# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("Correlated_basic", "Correlated_x", "Correlated_x_zglobal", "Correlated_x_zsubpop", "Correlated_x_zsubpop_zglobal", "Correlated_zglobal", "Correlated_zsubpop", "Correlated_zsubpop_zglobal", "Overdispersed_Stan", "Uncorrelated_basic", "Uncorrelated_x", "Uncorrelated_x_zglobal", "Uncorrelated_x_zsubpop", "Uncorrelated_x_zsubpop_zglobal", "Uncorrelated_zglobal", "Uncorrelated_zsubpop", "Uncorrelated_zsubpop_zglobal")

# load each stan module
Rcpp::loadModule("stan_fit4Correlated_basic_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_x_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_x_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_x_zsubpop_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_x_zsubpop_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_zsubpop_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Correlated_zsubpop_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Overdispersed_Stan_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_basic_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_x_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_x_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_x_zsubpop_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_x_zsubpop_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_zglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_zsubpop_mod", what = TRUE)
Rcpp::loadModule("stan_fit4Uncorrelated_zsubpop_zglobal_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
