# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit test.Rmd to modify this file

## ----setup, include=FALSE---------------------------------------------------------------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message = FALSE, fig.height = 4)
library(networkscaleup)
library(ggplot2)
set.seed(100)



## ----sim_pois_data_1, echo =TRUE, eval=FALSE--------------------------------------------------------------------------------------
# library(networkscaleup)
# make_ard(family = "poisson", n_i = 500, n_k = 20, N = 1e06)


## ----sim_pois_data_2, echo = TRUE-------------------------------------------------------------------------------------------------
sim_dat <- make_ard(n_i = 500, n_k = 20, N = 1e06,
                    p = 6,
                    p_local_nonzero = 2,
                    p_global_nonzero = 1,
                    family = "poisson")


## ----see-global-beta, echo=TRUE---------------------------------------------------------------------------------------------------
sim_dat$x_beta_global 


## ----fit_pois_data, echo = TRUE---------------------------------------------------------------------------------------------------
pois_fit <- fit_mle(sim_dat$ard, family = "poisson")

pois_fit$alphas[1:5] # the first 5 log degree estimates


## ---------------------------------------------------------------------------------------------------------------------------------
y_ukr <- read.csv("data/Ukraine_y_analysis.csv")
x_ukr <- read.csv("data/Ukraine_dem_cov_analysis.csv")
cov_names <- colnames(x_ukr)
y_ukr <- as.matrix(y_ukr)


## ----fit_pois_ukr, echo=TRUE, cache=TRUE------------------------------------------------------------------------------------------
pois_fit_ukr <- fit_mle(ard = y_ukr, family = "poisson")


## ----make-plot-cov-poisson, echo = TRUE, fig.cap="Local covariates", fig.pos='H'--------------------------------------------------
cov_plot <- cov_plots(
  ard = sim_dat$ard,
  model_fit = pois_fit,
  x_cov = sim_dat$x_cov,
  se = T
)

local_cov_plot <- cov_plot$Group_plot
global_cov_plot <- cov_plot$Respondent_plot


## ----plot-cov-poisson, echo = TRUE, fig.cap="Local covariates", fig.height=3, fig.pos='H'-----------------------------------------
local_cov_plot 


## ----plot-global-cov, echo=TRUE, fig.cap="Global covariates", fig.height=2.5, fig.pos='H'-----------------------------------------
global_cov_plot 


## ----fit-cov-sim, echo=TRUE-------------------------------------------------------------------------------------------------------
pois_fit_cov <- fit_mle(
  sim_dat$ard,
  x_cov_local = as.matrix(sim_dat$x_cov[, c(1, 3)]),
  x_cov_global = as.matrix(sim_dat$x_cov[, c(2)]),
  family = "poisson"
)


## ----get-cov-ukraine--------------------------------------------------------------------------------------------------------------
cov_pois <- cov_plots(
  ard = y_m,
  model_fit = pois_fit_ukr,
  x_cov = x,
  se = T
)

local_cov_plot_ukr <- cov_pois$Group_plot
global_cov_plot_ukr <- cov_pois$Respondent_plot


## ----plot-local-cov-ukr, echo=TRUE, fig.cap="Local covariates, Ukraine", fig.height=5, fig.pos='H'--------------------------------
local_cov_plot_ukr 


## ----plot-global-cov-ukr, echo=TRUE, fig.cap="Global covariates, Ukraine", fig.height=2.5, fig.pos='H'----------------------------
global_cov_plot_ukr


## ----fit-cov-ukr, echo=TRUE, cache=TRUE-------------------------------------------------------------------------------------------
pois_fit_ukr_cov <- fit_mle(
  y_m,
  x_cov_local = as.matrix(x[, c(1, 2, 4, 5, 6)]),
  x_cov_global = as.matrix(x[, c(3, 7, 8)]),
  family = "poisson"
)


## ----plot-tw-sim, fig.cap="TW Test",fig.pos='H', echo=TRUE, fig.height=2.5, fig.width=5-------------------------------------------
tw_test <- tw_group_corr_test(model_fit = pois_fit_cov, plot = TRUE)
tw_test$p_value
tw_test$tw_density_plot


## ----plot-tw-ukr, fig.cap="TW Test, Ukraine Data", fig.pos='H',fig.height=2.5, fig.width=5, echo=TRUE-----------------------------
tw_ukr <- tw_group_corr_test(model_fit = pois_fit_ukr_cov, plot = TRUE)
tw_ukr$p_value
tw_ukr$tw_density_plot


## ----root, echo = TRUE, fig.height=2.5, fig.cap="Hanging rootogram for simulated data."-------------------------------------------
pois_root <- hang_rootogram_ard(
  ard = sim_dat$ard,
  model_fit = pois_fit_cov,
  x_max = 100
) 
pois_root



## ----disp-sim, fig.height=2.5, fig.cap="Dispersion test for simulated data across subpopulations"---------------------------------
disp_test <- dispersion_metric(ard = sim_dat$ard, model_fit = pois_fit_cov)
disp_test$plots


## ----root-ukr, fig.height=3.5, fig.cap="Overall Rootogram for Ukraine Data"-------------------------------------------------------
pois_root_ukr <- hang_rootogram_ard(
  ard = y_m,
  model_fit = pois_fit_ukr_cov
)
pois_root_ukr


## ----fig.height=2.5, fig.cap="Dispersion test for Ukraine data across subpopulations"---------------------------------------------
disp_test_ukr <- dispersion_metric(ard = y_m, model_fit = pois_fit_ukr_cov)
disp_test_ukr$plots


## ----fitted-no-cov, echo=TRUE, fig.height=2.5, fig.cap="Plotting fitted residuals indicates lack of model fit when covariates are ignored."----

plot_fitted(ard = sim_dat$ard,
            model_fit = pois_fit,
            resid = "rqr") +
  labs(title = "Ignoring covariates")


## ----fitted-cov, echo=TRUE, fig.height=2.5, fig.cap="Incorporating covariates indicates improved model fit."----------------------
plot_fitted(ard = sim_dat$ard,
            model_fit = pois_fit_cov,
            resid = "rqr") +
  labs(title = "Including covariates")


## ----ukraine-cov, echo=TRUE, fig.height=2.5, fig.cap="Plotting fitted residuals indicates lack of model fit, after including covariates."----
plot_fitted(ard = y_m,
            model_fit = pois_fit_ukr_cov,
            resid = "rqr") +
  labs(title = "Ignoring covariates")


