---
title: "Networkscaleup: An R Package for Fitting and Evaluating Models 
for Aggregated Relational Data"
date: "2026-01-19"
abstract: >
  An abstract of less than 150 words.
draft: true
author:  
  - name: Quietest Quokka
    affiliation: University of Little Mates
    address:
    - Department of Letter Q
    - Somewhere, Australia
    url: https://www.britannica.com/animal/quokka
    orcid: 0000-1721-1511-1101
    email:  qquo@ulm.edu
  - name: Bounciest Bilby
    affiliation:
    - University of Little Mates
    - University of Aussie Animals
    address:
    - Department of Letter Q, Somewhere, Australia
    - Department of Marsupials, Somewhere, Australia
    url: https://www.britannica.com/animal/bilby
    email: bbil@ulm.edu
    orcid: 0000-0002-0912-0225
type: package
output: 
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Introduction

- ARD is ....
- ARD is widely used in ....

- In this paper we will review how to use `networkscaleup` to fit and diagnose
popular models for ARD. 

- Aim to provide a suite of functions for applied practitioners who
wish to use the models for their own ARD, and understand how 
to compare and contrast popular models.

# Background

- A brief description of ARD and the network scale up method in general. 

- Then this will be followed by the goal of collecting widely used models
for this data, and providing software to fit these models quickly 
(fit and fail fast). 


# The networkscaleup package

- Describe an overview of the functionality of the package and the general
formatting

- Describe how to simulate ARD using the package

- Describe how to read in and process real ARD in this 
package (do we need this, we don't really do much for this?)


# Fitting Models to ARD

- Describe the key functionality we have to do this

- A worked example with simulated data from the models in the package

- A worked example with real data, where we fit these models.


# Evaluating ARD Models


- Describe the key functions for this in the package

- Continue the two worked examples from before, illustrating the uses of the
package for these tasks specifically


# Summary

- A summary of what we have done, and why we have done it
